### PR TITLE
Cache parsed expression

### PR DESCRIPTION
**Pull request by Rfank2021**
We tested that cache ast parsing result reduced more than 50% run time for our user case, it would be great if it can be merged.

The cache is an option which is disabled by default, so current user will not be affected.

### CODE REVIEW

**Comment by Rfank2021** [comment]
@danthedeckie do you have time to check this? CodeFactor issues are not related to the code change.

**Comment by Rfank2021** [comment]
Found a way to extend SimpleEval class, this CR is not needed.

**Comment by n1ngu** [comment]
Very much related https://github.com/danthedeckie/simpleeval/pull/60

**Comment by danthedeckie** [comment]
I'm closing this PR, as 0.9.13 now includes a separated `parse` and `eval` methods, which allows you cache the parsed AST tree outside of SimpleEval pretty easily.

**Pull request closed without merging**
