### PR TITLE
Correctly validate evaluation expression input

### LINKED ISSUE #58: Raise error when multi line expression is passed for evaluation
Using `simple_eval` method expression like `True\nFalse` is evaluated to True, `False\nTrue` to False.

It looks like only the first statement is taken from AST for evaluation.
https://github.com/danthedeckie/simpleeval/blob/b47858d7153a05f64da16c4425c38f481e510d12/simpleeval.py#L328

I suggest that an exception must be raised in case where there are multiple statements to be sure that passed expression is evaluated correctly.

### PR DESCRIPTION
**Pull request by PPakalns**
* There must be exactly one statement in input
* Given statement must be an expression (assignment, augmented  assignment, etc. are not allowed)

Resolves #58 #65 #67

### CODE REVIEW

**Comment by PPakalns** [comment]
I believe that these issues found by CodeFactor can be fixed in other pull request as I did not introduce them or I used the same style that was already used by this library.
If you do not agree I can of course fix these reported errors.

**Comment by jeffreyscottgraham** [comment]
Is this issue dead?

**Comment by PPakalns** [comment]
@jeffreyscottgraham 
There are users that are already dependent on the way how this library is implemented.  [See this comment and the whole thread.](https://github.com/danthedeckie/simpleeval/issues/65#issuecomment-571459903)

Looks like 2.0 version of this library needs to be created. Probably, if someone need some additional functionality, then new fork of this library must be created because the activity on this project is very low.

**Comment by kurtmckee** [comment]
@danthedeckie I recommend closing this PR due to its age.

**Comment by danthedeckie** [comment]
Yeah, this is a 2.0 issue.

**Pull request closed without merging**
